# coding: utf-8
import sys
sys.path.append('.')

BROKER_HOST = "srv-4.yottos.com"
BROKER_PORT = 5672
BROKER_USER = "click-redirect"
BROKER_PASSWORD = "123qwe"
BROKER_VHOST = "click-redirect"
BROKER_CONNECTION_TIMEOUT = 1
BROKER_CONNECTION_MAX_RETRIES = 2
CELERY_RESULT_BACKEND = "cache"
CELERY_CACHE_BACKEND = 'memcached://127.0.0.1:11211/'
CELERY_IMPORTS = ("tasks",)
CELERY_TASK_RESULT_EXPIRES = 3600
CELERYD_CONCURRENCY = 2
CELERY_TIMEZONE = 'Europe/Kiev'
CELERY_ENABLE_UTC = False
CELERY_QUEUE_HA_POLICY = 'all'
CELERYD_MAX_TASKS_PER_CHILD = 10
